### PR TITLE
redirect __call__ to predict

### PR DESCRIPTION
**Pull request by PhilipMay**
PR for #136

### CODE REVIEW

**Comment by PhilipMay** [comment]
CI is green - can be merged from my point of view.

**Comment by lewtun** [comment]
Hey @PhilipMay thanks for this fix! We just merged a long-standing PR in #112 which means you have a small merge conflict to resolve - would you mind fixing that and then we can merge?

**Comment by PhilipMay** [comment]
> would you mind fixing that and then we can merge?

Done. CI is green...

**Review by lewtun — APPROVED** [review]
Thanks for the fix!

**Pull request merged**
