### PR TITLE
Fix seed in `trainer.py`

### PR DESCRIPTION
**Pull request by danielkorat**

### CODE REVIEW

**Review by lewtun — APPROVED** [review]
Thanks for the fix, LGTM!

For context to others: @danielkorat noticed that our `run_fewshot.py` script wasn't producing reproducible results when the seed was fixed. This PR addresses that

**Comment by lewtun** [comment]
Ah, would you mind running `make style && make quality` and pushing again?

**Comment by danielkorat** [comment]
@lewtun Done :)

**Review by tomaarsen — CHANGES_REQUESTED** [review]
Well spotted!

Can we get a similar fix applied for the distillation trainer?
https://github.com/huggingface/setfit/blob/6ee9b9d9efbffb2bcc364ba521007816ee89b6cf/src/setfit/trainer_distillation.py#L138

**Review by danielkorat — COMMENTED** [review]
done

**Review by tomaarsen — APPROVED** [review]
Thanks!

**Pull request merged**
