### PR TITLE
Add docs skeleton

### PR DESCRIPTION
**Pull request by lewtun**
This PR adds a basic skeleton to build the docs on hf.co :)

TODO

- [x] Get the `HUGGINGFACE_PUSH` token added
- [x] Make sure the docs build with the correct version in `docs-build-dev`
- [ ] ~~Add the docs link to repo info~~ (Will do this once the docs are ready for public consumption)

### CODE REVIEW

**Comment by tomaarsen** [comment]
I see now that I wasn't the only one who experienced some issues with the HF Doc Builder bot. Do you know how to get it to build properly?

**Comment by lewtun** [comment]
> I see now that I wasn't the only one who experienced some issues with the HF Doc Builder bot. Do you know how to get it to build properly?

Haha yes, I'm waiting for one of the HF admins to enable the secret that pushes the builds to these repos:

* PRs => https://github.com/huggingface/doc-build-dev
* On `main` => https://github.com/huggingface/doc-build

FYI I also added you to the PR in one of the commits since I built on top of your fork - I hope that is OK!

**Comment by tomaarsen** [comment]
Yeah, that's more than OK! 
I did not realise the comment bot required some intervention by HF admins.

**Comment by tomaarsen** [comment]
There were some undefined titles here:
image
I've modified it to match the [transformers style](https://huggingface.co/docs/transformers), with a few placeholders. We can eventually disseminate the information from Quickstart into the tutorials or how-to section.

I'm not very attached to exactly using this format. For our purposes, we may even be better off merging "How-to guides" and "tutorial". Thoughts on this?

Regardless, I think this is ready to merge. We can add other PRs to improve on the documentation.

**Review by tomaarsen — APPROVED** [review]

**Comment by lewtun** [comment]
Thanks for the fixes! The tutorials vs how-to guides is inspired from the [Divio documentation system](https://documentation.divio.com/structure/): 

Screenshot 2023-02-27 at 10 05 48

I'm happy to merge the two as you suggest, but let's first see if there's a need to keep learning-oriented vs problem-oriented content separate :) 

One other advantage for sticking with the Divio system is that it has some familiarity with some (but not all) of our other libraries like `datasets` and `optimum`

**Comment by tomaarsen** [comment]
Ahh, I see. That's a useful reference to keep handy. I suspect we're best off keeping them separate, then.

**Pull request merged**
