### PR TITLE
Add SetFitModel.to

### LINKED ISSUE #193: picking which GPU to run the model on
Hello,
First, thanks for the great lib and great work. I was wondering if there is a way to pick which cuda device to run my model on ? tried to search for it but it seems to automatically detect and just pick.

### PR DESCRIPTION
**Pull request by jegork**
Fixes #193, #206

Add a simple method to move the body and/or head to the specified device.

### CODE REVIEW

**Review by tomaarsen — APPROVED** [review]
Note that this does mean that we differ from e.g. torch, which creates a moved copy rather than moving the e.g. tensor itself to a different device. (See the Note in the [`Tensor.to` docs](https://pytorch.org/docs/stable/generated/torch.Tensor.to.html) for details on how torch handles `to`)

That said, I don't mind the difference much.

**Review by lewtun — APPROVED** [review]
This is wonderful @jegork - I was actually annoyed by not being able to do this myself recently :)

Thank you for the clean implementation and for adding tests ❤️ !

**Comment by lewtun** [comment]
Hey @jegork we merged some changes to the CI before I merged your PR and it turns out some of the tests fail on `main`. I've reverted your change for now, but would you mind opening a new PR with your contribution once #234 is merged?

Thanks and sorry for the bother!

**Comment by connormeaton** [comment]
I found my way to this page because I am having trouble running a setfit model locally on cpu (I trained on a GPU instance, saved with joblib). I believe this PR attempts to solve this issue. How do I use this code to run my gpu trained model on cpu?

Here is my save code:
```
joblib.dump(trainer, 'model.joblib')
```
Here is my error when running:
```
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
```

I get the same error when loading both of the ways below:
```
new_trainer = joblib.load('model.joblib')
torch.load('model.joblib', map_location='cpu')
torch.load('model.joblib', map_location=torch.device('cpu'))
```

**Pull request merged**
