### PR TITLE
Fix/input type hint

### PR DESCRIPTION
**Pull request by Yongtae723**
I think the type hint of predict and predict_proba is not correct.
It's python, so it doesn't cause errors, but it might confuse readers, so made this PR.

The reasons for this PR are as follows

Regarding inputs:
1. `SentenceTransformer.encode` accept `Union[List[str], str]`, not `torch.Tensor` as you can see [here](https://github.com/UKPLab/sentence-transformers/blob/0b5ef4be93d2b21de3a918a084b48aab6ba48595/sentence_transformers/SentenceTransformer.py#L111)
2.  If the type of x_test is `str`, errors occur since the size of embedding is different from the size expected by the model head.
From type these reason, the type of x_test should be   `List[str]`

As for the output, the reason is clear, so I will omit it.

### CODE REVIEW

**Review by tomaarsen — APPROVED** [review]
LGTM, well spotted

**Review by lewtun — APPROVED** [review]
Thanks for the fix!

**Comment by lewtun** [comment]
Ah, there's some conflicts from previous PRs getting merged - would you mind resolving them and pushing again @Yongtae723 ?

**Comment by Yongtae723** [comment]
Absolutely no problem

**Comment by Yongtae723** [comment]
@lewtun 
Hi lewtun

I resolved it. please merge it if there are no problems.

thank you
Yongtae

**Comment by lewtun** [comment]
Thanks for the fix @Yongtae723!

**Pull request merged**
