### PR TITLE
Various cleanups; type hint fixes incl. corresponding to PEP 484

### PR DESCRIPTION
**Pull request by tomaarsen**
Hello!

## Pull request overview
* Fix type hints in various locations, primarily adding `Optional` in accordance to [PEP 484](https://peps.python.org/pep-0484/#union-types).
* Various small cleanups:
  * Removing unnecessarily duplicate code
  * Using a backtick around class/function/variable names in logs and warnings more consistently.

## Details
[PEP 484](https://peps.python.org/pep-0484/#union-types) now states that a type hint of `int = None` is no longer correct. In previous versions, this would have been allowed, as it implicitly becomes `Optional[int] = None`. This was later changed, requiring us to be explicit with `Optional`.

Each of the changes are small, and for the most part ought to speak for themselves. Please let me know if you have any questions and feel free to review.

- Tom Aarsen

### CODE REVIEW

**Review by lewtun — APPROVED** [review]
Thanks for all these fixes @tomaarsen ❤️ ! They LGTM so happy to merge once we resolve the conflicts from some prior PRs getting merged

**Comment by tomaarsen** [comment]
I'll get right on that!

**Comment by lewtun** [comment]
Sorry to be a pain, but only just getting back to this now and there's a new round of merge conflicts to resolve. If you don't mind fixing them, I'll merge this right away!

**Comment by tomaarsen** [comment]
It seems like we're experiencing some issues with the latest `isort` version that released some ~45 minutes ago, see https://github.com/huggingface/setfit/actions/runs/3679204969/jobs/6223374484 and https://github.com/PyCQA/isort/issues/2031. I've prepared a PR on isort to resolve the issue: https://github.com/PyCQA/isort/pull/2032.

**Pull request merged**
