### PR TITLE
Fix bug where SetFitHead not moved to non-cuda devices on init

### PR DESCRIPTION
**Pull request by ajmssc**
On my M2 macbook the SetFitHead is not moved to `mps` on init. 
This is because of a typo in the ternary operation to determine the GPU.

### CODE REVIEW

**Comment by ajmssc** [comment]
@tomaarsen

**Comment by osanseviero** [comment]
cc @pcuenca as well

**Review by pcuenca — APPROVED** [review]
Looks good to me! Thank you 🙌

**Comment by ajmssc** [comment]
@pcuenca you're gonna have to do the merging because I don't have that option

**Comment by pcuenca** [comment]
@ajmssc I know! I wanted to wait a few hours in case @tomaarsen wanted to comment, merging now :)

**Comment by ajmssc** [comment]
@tomaarsen @pcuenca what do you want to do with this PR?

**Comment by tomaarsen** [comment]
Hello!

Big apologies for the long delay - I should have gotten to this PR much sooner.
Well spotted, and the fix looks solid as well. I'll merge it in a minute & include it in an upcoming release.

- Tom Aarsen

**Pull request merged**
