### PR TITLE
fixed spell errors in code example

### PR DESCRIPTION
**Pull request by Gladiator07**
Fixed spell errors of `contrastive` in the code examples

### CODE REVIEW

**Review by tomaarsen — CHANGES_REQUESTED** [review]
Could you perhaps include this typo in this PR as well?
https://github.com/huggingface/setfit/blob/main/scripts/setfit/run_fewshot_distillation.py#L231

Looks good otherwise!

**Comment by Gladiator07** [comment]
Hi @tomaarsen, did the changes.

**Review by tomaarsen — APPROVED** [review]
LGTM!

**Review by lewtun — APPROVED** [review]
Thanks for the fixes @Gladiator07 !

**Pull request merged**
