### PR TITLE
Don't use deprecated `DatasetFilter` + update deps

### PR DESCRIPTION
**Pull request by Wauplin**
`DatasetFilter` has been deprecated since version `0.21.0` and will be removed in next version of `huggingface_hub` (0.24.0). This PR updates the code to get rid of `DatasetFilter` and use plain args instead. I also took the liberty to update the minimal `huggingface_hub` version. For the record transformers/datasets/diffusers latest versions are already set to use 0.22.0+ so should be fine. I also removed tests for Python3.7 since latest versions don't support it (since June 2023).

Related deprecation PR: https://github.com/huggingface/huggingface_hub/pull/2028.

cc @tomaarsen

### CODE REVIEW

**Comment by tomaarsen** [comment]
I appreciate it. I'll look at this PR (and others on SetFit) after the v3.0 Sentence Transformers release (scheduled this month). Apologies for the delays.

- Tom Aarsen

**Comment by Wauplin** [comment]
No worries, that's fine I think. Just wanted to make sure we don't forget.

**Review by julien-c — APPROVED** [review]
lgtm!

**Comment by TimbusCalin** [comment]
No updates on this?

**Comment by tomaarsen** [comment]
Hello!

Apologies for the delay! I've merged these changes into `main` and resolved the remaining outstanding issues as well. I expect this'll all be included in a release quite soon (this week?). Thanks a bunch for making this PR!

- Tom Aarsen

**Pull request merged**
